### ISSUE TITLE
Display misplaced when text content has emoji symbols

### ISSUE THREAD

**Issue by cdxjcl** [agavrilov/cursive_buffered_backend#10]
I created a simple dialog in Cursive where the label and button text start with emoji 🖼️ and I got this:
![image](https://user-images.githubusercontent.com/25812821/187399029-ec8564a6-40af-4352-98d8-ba8fafd8d273.png)
Without this buffered backend it works fine:
![image](https://user-images.githubusercontent.com/25812821/187399711-cdc982b6-74fd-4039-87ca-aef21288e596.png)

My backend is crossterm-backend and I am using Windows Terminal on Windows 11.

**Comment by agavrilov** [comment]
I did try to pinpoint where the issue happens. It looks like it is not completely a buffered_backend fault. If I use 2 emoji with a pure 'crossterm-backend' and no buffered backend, I got the text truncated on the button:
![image](https://user-images.githubusercontent.com/3209180/189775136-932091af-d584-4d21-9ad2-f87e7d50fdd1.png)
I'll try to investigate further...
